version: '3'
services:

  servicoa:
    build:
      context: .
      dockerfile: Dockerfile.servicoa
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
    networks:
      - networkservicos

  servicob:
    build:
      context: .
      dockerfile: Dockerfile.servicob
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
    networks:
      - networkservicos

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - networkservicos

networks:
  networkservicos:
    driver: bridge
